include: package:very_good_analysis/analysis_options.yaml
linter:
  rules:
    public_member_api_docs: false
analyzer:
  errors:
    avoid_catches_without_on_clauses: ignore
    deprecated_member_use_from_same_package: ignore
    document_ignores: ignore
  exclude:
    - "**/*.g.dart"
    - "build/**"
  plugins:
    - custom_lint

custom_lint:
  enable_all_lint_rules: true